server:
  port: 8080
spring:
  application:
    name: grpc-server
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
    com.memposit: debug

grpc:
  server:
    port: 9000
